### ISSUE TITLE
replaceXMLReservedWords must be optional

### ISSUE THREAD

**Issue by dmitry-rivlin-vrp** [zabroseric/sfdc-xml-parser#9]
invocation of method "replaceXMLReservedWords" must be optional. On large XML files we have LIMIT Exception related to REGEX

**Comment by zabroseric** [comment]
This exception is thrown when the XML is larger than 1MB. There are a couple regex expressions that are used, both in the **replaceXMLReservedWords** and the **read** method both to replace the tag names and clean up the XML so that spacing between tags does not cause issues for the inbuilt XmlStreamReader.

These can either have an optional flag or alternatively, altered to not require regex. However, I have noticed that when these expressions are removed, we move into CPU timeout and heap size limits when the size is greater than 1.5MB.

This would require a lot of optimisation for XML file sizes that may not be commonly used. If the issue gets more upvotes I can look into this. However, I would recommend reducing the size of the XML if possible by:

- Stripping out irrelevant nodes
- Paging

Alternatively, I'm more than happy for you to create a PR with these optimisation improvements.

**Comment by zabroseric** [comment]
There are two methods that use regex expressions. The first one **replaceXMLReservedWords** replaces the served node names and adds a suffix, the other removes white space between tags in order to fix issues with the XMLReader class.

Both of these have the ability to fail when the XML file is too large. As a solution, I have introduced the the method **sanitize** and **unsanitize** where you can turn both of these on and off as you choose. I've also made other performance improvements as well to help with larger file sizes. Please see more info here: https://github.com/zabroseric/sfdc-xml-parser#sanitize-default--unsanitize

Let me know if that works.

```java
Map<String, Object> objElements = (Map<String, Object>) XML.deserialize(myVeryBigXMLString)
  .unsanitize()
  .toObject();
```
